version: "3"

services:


  web:
    container_name: weddpics_web
    hostname: weddpics
    build:
      context: .
    environment:
      - FLASK_APP=$FLASK_APP
      - FLASK_ENV=$FLASK_ENV
      - APP_SETTINGS=$APP_SETTINGS
      - MONGODB_DATABASE=$MONGODB_DATABASE
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
    volumes:
    - ${PWD}:/home/weddpics
    ports:
    - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - galleryfrontend
      - gallerybackend

  mongodb:
    image: mongo:latest
    restart: on-failure
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
      MONGODB_DATA_DIR: $MONGODB_DATA_DIR
      MONDODB_LOG_DIR: $MONDODB_LOG_DIR
    ports:
      - "27017:27017"
    networks:
      - gallerybackend

  mongo_express:
    image: mongo-express
    ports:
      - "8081:8081"
    links:
      - mongodb
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=$ME_CONFIG_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD=$ME_CONFIG_BASICAUTH_PASSWORD
      - ME_CONFIG_MONGODB_PORT=$ME_CONFIG_MONGODB_PORT
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=$ME_CONFIG_MONGODB_ENABLE_ADMIN
      - ME_CONFIG_MONGODB_SERVER=$ME_CONFIG_MONGODB_SERVER
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$ME_CONFIG_MONGODB_ADMINPASSWORD
    networks:
      - gallerybackend


networks:
  galleryfrontend:
    driver: bridge
  gallerybackend:
    driver: bridge
